const profiles = [
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-1.jpg",
    houseImage: "../images/flat-1.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "popular",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-2.jpg",
    houseImage: "../images/flat-2.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "new house",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-3.jpg",
    houseImage: "../images/flat-3.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "best deals",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-4.jpg",
    houseImage: "../images/flat-4.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "new house",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-5.jpg",
    houseImage: "../images/villa-1.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "new house",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-6.jpg",
    houseImage: "../images/villa-2.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "best deals",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-7.jpg",
    houseImage: "../images/villa-3.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "popular",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-8.jpg",
    houseImage: "../images/villa-4.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "best deals",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-8.jpg",
    houseImage: "../images/villa-5.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "best deals",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-10.jpg",
    houseImage: "../images/villa-6.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "popular",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-11.jpg",
    houseImage: "../images/flat-5.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "best deals",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-12.jpg",
    houseImage: "../images/flat-6.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "popular",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-13.jpg",
    houseImage: "../images/flat-7.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "best deals",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-14.jpg",
    houseImage: "../images/flat-8.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "new house",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-15.jpg",
    houseImage: "../images/flat-9.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "popular",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-16.jpg",
    houseImage: "../images/flat-10.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "best deals",
  },
  {
    name: "Dianne Rusell",
    address: "Manchester, Kentucky",
    review: "lorem",
    article: "lorem",
    image: "../images/profile-17.jpg",
    houseImage: "../images/flat-11.jpg",
    house: "Roselands House",
    price: "$ 23,000,000",
    category: "new house",
  },
];
